# ============================================================
# Amil Functional Annotation — Seurat/CellChat helper
# Generated by 08_merge_annotate.py v3
# ============================================================

library(Seurat)
library(dplyr)

GENE_LISTS_DIR <- "/scratch/dark_genes/annotation_pipeline/runs/Amil_20260711/08_final/gene_lists"
MASTER_TABLE   <- "/scratch/dark_genes/annotation_pipeline/runs/Amil_20260711/08_final/Amil_master_annotation.tsv"

# ── Load master annotation ────────────────────────────────
annot <- read.table(MASTER_TABLE, sep="\t", header=TRUE,
                    stringsAsFactors=FALSE, quote="")
cat("Master table:", nrow(annot), "genes x", ncol(annot), "columns\n")

# ── Useful lookup vectors ─────────────────────────────────
# Best human gene name for each Amil gene
amil_to_human <- setNames(annot$best_human_gene_name, annot$amil_gene_id)
amil_to_human <- amil_to_human[amil_to_human != ""]

# Protein group per gene
amil_to_group <- setNames(annot$protein_group, annot$amil_gene_id)

# CellChat role per gene
amil_to_cellchat <- setNames(annot$cellchat_role, annot$amil_gene_id)

# ── Load gene lists ───────────────────────────────────────
list_files <- list.files(GENE_LISTS_DIR, pattern="\\.txt$", full.names=TRUE)
gene_lists <- lapply(list_files, readLines)
names(gene_lists) <- gsub("\\.txt$", "", basename(list_files))
cat("Gene lists loaded:", length(gene_lists), "\n")
for (nm in names(gene_lists)) {
  cat("  ", nm, ":", length(gene_lists[[nm]]), "genes\n")
}

# ── Score cells with AddModuleScore ──────────────────────
# Replace `seurat_obj` with your Seurat object name
# Genes present in the atlas
# present <- rownames(seurat_obj)
# gene_lists_filt <- lapply(gene_lists, function(g) g[g %in% present])
#
# for (group in names(gene_lists_filt)) {
#   n <- length(gene_lists_filt[[group]])
#   if (n >= 5) {
#     seurat_obj <- AddModuleScore(seurat_obj,
#                                   features = list(gene_lists_filt[[group]]),
#                                   name = paste0(group, "_score"))
#     cat("Scored:", group, "(", n, "genes)\n")
#   }
# }

# ── CellChat custom DB setup ──────────────────────────────
# Ligands and receptors for custom CellChatDB construction
# ligands   <- gene_lists[["CellChat_Ligand"]]
# receptors <- gene_lists[["CellChat_Receptor"]]
# candidates <- gene_lists[["CellChat_Receptor_candidate"]]

cat("\nDone.\n")
